# Generated by Django 5.2.4 on 2025-08-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('flag', models.BooleanField(default=True)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='sistema.persona')),
            ],
        ),
    ]
