# Generated by Django 5.2.4 on 2025-08-10 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='persona',
            new_name='usuario',
        ),
    ]
