# Generated by Django 5.2.4 on 2025-08-13 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('flag', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='especialidad',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='sistema.profesion'),
        ),
    ]
