# Generated by Django 5.2.4 on 2025-08-15 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_profesion_especialidad_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectosnegocio',
            name='experiencia',
            field=models.TextField(blank=True),
        ),
    ]
