# Generated by Django 5.2.4 on 2025-08-15 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0004_especialidad_profesion_and_more'),
        ('sistema', '0004_aspectosnegocio_experiencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Especialidad',
        ),
        migrations.DeleteModel(
            name='Profesion',
        ),
    ]
