# Generated by Django 5.2.4 on 2025-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0005_delete_especialidad_delete_profesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectosnegocio',
            name='permite_presencial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspectosnegocio',
            name='permite_virtual',
            field=models.BooleanField(default=False),
        ),
    ]
