# Generated by Django 5.2.4 on 2025-11-24 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_aspectosnegocio_permite_presencial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspectosnegocio',
            name='precio_online',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='aspectosnegocio',
            name='precio_presencial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
