# Generated by Django 5.2.4 on 2025-08-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacion', '__first__'),
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.TextField(blank=True)),
                ('flag', models.BooleanField(default=True)),
                ('aspecto_negocio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='sistema.aspectosnegocio')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='sistema.especialidad')),
                ('organizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='organizacion.organizacion')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to='sistema.persona')),
            ],
        ),
    ]
