# Generated by Django 5.2.4 on 2025-08-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0002_rename_persona_profesional_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='experiencia',
        ),
    ]
