# Generated by Django 5.2.4 on 2025-08-15 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0004_especialidad_profesion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='aspecto_negocio',
            new_name='aspectos_negocio',
        ),
    ]
