# Generated by Django 5.2.4 on 2025-11-05 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_persona_cliente_usuario'),
        ('organizacion', '0001_initial'),
        ('profesional', '0005_rename_aspecto_negocio_profesional_aspectos_negocio'),
        ('sistema', '0005_delete_especialidad_delete_profesion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='flag',
            field=models.BooleanField(default=True, help_text='Indica si la especialidad está activa.'),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='profesion',
            field=models.ForeignKey(help_text='Profesión a la que pertenece esta especialidad.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidades', to='profesional.profesion'),
        ),
        migrations.AlterField(
            model_name='profesion',
            name='flag',
            field=models.BooleanField(default=True, help_text='Indica si el registro está activo o no.'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='aspectos_negocio',
            field=models.ForeignKey(help_text='Aspectos de negocio relacionados con este profesional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='sistema.aspectosnegocio'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='especialidad',
            field=models.ForeignKey(blank=True, help_text='Especialidad que ejerce el profesional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='profesional.especialidad'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='flag',
            field=models.BooleanField(default=True, help_text='Indica si el profesional está activo en el sistema.'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='organizacion',
            field=models.ForeignKey(blank=True, help_text='Organización o institución a la que pertenece el profesional.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profesionales', to='organizacion.organizacion'),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='usuario',
            field=models.OneToOneField(help_text='Referencia al usuario asociado (modelo Usuario).', on_delete=django.db.models.deletion.CASCADE, related_name='profesional', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProfesionalCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='activo', help_text='Estado de la relación (activo, finalizado, suspendido, etc.)', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_profesional', to='cliente.cliente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_cliente', to='profesional.profesional')),
            ],
            options={
                'verbose_name': 'Relación Profesional-Cliente',
                'verbose_name_plural': 'Relaciones Profesionales-Clientes',
                'unique_together': {('profesional', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisor', models.CharField(choices=[('profesional', 'Profesional'), ('cliente', 'Cliente')], max_length=20)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='profesional.profesionalcliente')),
            ],
            options={
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(help_text='Fecha y hora programada de la cita.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Motivo o descripción de la cita.', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('relacion', models.ForeignKey(help_text='Relación profesional-cliente a la que pertenece esta cita.', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='profesional.profesionalcliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-fecha'],
            },
        ),
    ]
