# Generated by Django 5.2.4 on 2025-11-23 23:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0006_alter_especialidad_flag_alter_especialidad_profesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='calificacion_cliente',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='cita',
            name='calificacion_profesional',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
